#!/bin/bash

sudo apt-get install ca-certificates curl gnupg lsb-release
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable" | sudo tee -a /etc/apt/sources.list.d/debian.list # $(lsb_release -cs) > /dev/null

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
#https://docs.docker.com/desktop/install/debian/
#https://desktop.docker.com/linux/main/amd64/docker-desktop-4.11.0-amd64.deb?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-linux-amd64
#https://docs.docker.com/desktop/get-started/#credentials-management

gpg --generate-key
/home/butt/.password-store/
systemctl --user enable docker-desktop
systemctl --user start docker-desktop
docker compose version
docker --version
docker version
