#!/bin/bash
function SIG { #cor] [simbolo] [msgm1] [msgm2]
	end="\e[0m" ; bef="\n\e[1;34m[$end" ; aft="\e[1;34m]$end"
	case $1 in
		"err") cor="\e[1;31;1m" ;;
		"red") cor="\e[1;31;1m" ;;
		"gre") cor="\e[1;32;1m" ;;
		"pur") cor="\e[1;35;1m" ;;
		"whi") cor="\e[1;37;1m" ;;
		*)	   bef="\e[1;34m[$end\e[1;37;1m"
	esac
	if [ "$1" = "err" ];then
		echo -en "$bef$cor$2$end$aft\e[5;31m $3$end\e[1;37m $4$end"
	else
		echo -en "$bef$cor$2$end$aft\e[1;37m $3$end $4"
	fi
}
function continuo { # [no_ask or padrao] [msgm]
	if [ "$1" != "no_ask" ];then
		msgm="$2";[ -z "$2" ] &&	msgm="Continuar"
		SIG whi ">>" "$msgm" ; SIG n "y/n/pular" "Padrao:$1 ?"
		read -t15 -n1 opsao
		[ -z "$opsao" ] &&	opsao="$1"
		[[ "$opsao" = "y" || "$opsao" = "Y" ]] &&	return 0
		[[ "$opsao" = "p" || "$opsao" = "P" ]] &&	return 1
		exit 1
	fi

}
if [[ -n "$1" ]] ;then
	SIG whi ">>" "Instalação automatica." "Insira o padrao "; SIG n "y/n/p/no_ask";SIG n "Padrao:n" "?"
	read -t15 -n6 padrao ;[ -z "$padrao" ] &&	padrao="n"
else
	padrao="$1"
fi
pasta="Linux_install"
if continuo $padrao;then
	echo -en "\n"
	git clone "https://github.com/fabriciobuttbutt/$pasta.git"
	sleep 3
	cd Linux_install
	if continuo $padrao "Fase Geral. Continuar? ";then
		comando="sudo bash s_install_geral $padrao"
		eval $comando;	fi
	if continuo $padrao "Fase Office. Continuar? ";then
		comando="sudo bash s_install_office $padrao"
		eval $comando;	fi
	cd ..
	[ -d $pasta ] && rm -rd $pasta

fi
